spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
        
  devtools:
    restart:
      exclude:static/**,public/**
            
logging:
  level:
    root: DEBUG            